//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTLS_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_GorevlerPersonel
    {
        public int ID { get; set; }
        public Nullable<int> Gorev_ID { get; set; }
        public Nullable<int> Personel_ID { get; set; }
        public Nullable<System.DateTime> Zaman { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> Durum { get; set; }
        public Nullable<int> dlt { get; set; }
        public Nullable<System.DateTime> dlt_Zaman { get; set; }
    }
}
