//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTLS_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Bolgeler
    {
        public int ID { get; set; }
        public Nullable<int> Harita_ID { get; set; }
        public string BolgeAdi { get; set; }
        public Nullable<int> Anchor1_X { get; set; }
        public Nullable<int> Anchor1_Y { get; set; }
        public Nullable<int> Anchor1_Z { get; set; }
        public Nullable<int> Anchor2_X { get; set; }
        public Nullable<int> Anchor2_Y { get; set; }
        public Nullable<int> Anchor2_Z { get; set; }
        public Nullable<int> Anchor3_X { get; set; }
        public Nullable<int> Anchor3_Y { get; set; }
        public Nullable<int> Anchor3_Z { get; set; }
        public Nullable<int> AnchorMaster_X { get; set; }
        public Nullable<int> AnchorMaster_Y { get; set; }
        public Nullable<int> AnchorMaster_Z { get; set; }
        public Nullable<int> dlt { get; set; }
        public Nullable<System.DateTime> dlt_Zaman { get; set; }
        public Nullable<int> Anchor1_ID { get; set; }
        public Nullable<int> Anchor2_ID { get; set; }
        public Nullable<int> Anchor3_ID { get; set; }
        public Nullable<int> AnchorMaster_ID { get; set; }
        public string Anchor1_Ip { get; set; }
        public string Anchor2_Ip { get; set; }
        public string Anchor3_Ip { get; set; }
        public string AnchorMaster_Ip { get; set; }
    }
}
