//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTLSServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Ayarlar
    {
        public int ID { get; set; }
        public string Com { get; set; }
        public Nullable<int> BaglantiHizi { get; set; }
        public string YetkiliMailleri { get; set; }
        public string AcilDurumMailSablonu { get; set; }
        public Nullable<int> AlarmMailGonder { get; set; }
        public string Port { get; set; }
        public Nullable<int> HaberlesmeTuru { get; set; }
        public Nullable<int> Tolerans { get; set; }
        public Nullable<double> Oran { get; set; }
    }
}
