//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTLSServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Haritalar
    {
        public int ID { get; set; }
        public string HaritaAdi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> Resim_w { get; set; }
        public Nullable<int> Resim_h { get; set; }
        public Nullable<int> Harita_w { get; set; }
        public Nullable<int> Harita_h { get; set; }
        public Nullable<int> dlt { get; set; }
        public Nullable<System.DateTime> dlt_Zaman { get; set; }
        public Nullable<int> Map_ID { get; set; }
        public Nullable<int> Oran { get; set; }
    }
}
