//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTLSServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Personel
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<int> Departman_ID { get; set; }
        public Nullable<int> Gorev_ID { get; set; }
        public string TagNo { get; set; }
        public string Aciklama { get; set; }
        public string KamraIp { get; set; }
        public Nullable<int> Firma_ID { get; set; }
        public string TagTipi { get; set; }
        public Nullable<int> dlt { get; set; }
        public Nullable<System.DateTime> dlt_Zaman { get; set; }
        public string RFID_Tag { get; set; }
        public Nullable<int> OdaNo { get; set; }
        public Nullable<int> OdaIslem { get; set; }
        public Nullable<System.DateTime> OdaIslemTarih { get; set; }
    }
}
